# -*- coding: utf-8 -*-
"""INFO450 Final Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tBkIJFAKt3HPEztvE-15dtvkVw7UYdKA

# Data Cleaning/Preparation
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('IPUMS.csv') #Imports the csv file as df
df_occ = pd.read_csv('Occupation Codes.csv') #Imports the csv file as df_occ

df['OCC'] = df['OCC'].astype(str) #Converts the integer column in the occ dataframe to string to match the rest of the data
merged_df = pd.merge(df, df_occ, left_on='OCC', right_on='OCC Code', how='left') #Merges the two dataframes
print(merged_df.head())

cleaned_df = merged_df.dropna() #Removes any null values
cleaned_df = cleaned_df[~(cleaned_df.astype(str) == '999').any(axis=1)] #Removes any remaining values of '999'
print(cleaned_df.head())

"""# Feature Engineering"""

cleaned_df = cleaned_df.rename(columns={'INCWAGE': 'AnnualIncome'}) #Renames the INCWAGE column to AnnualIncome
cleaned_df['HourlyWage'] = cleaned_df['AnnualIncome'] / (cleaned_df['UHRSWORKT'] * cleaned_df['WKSWORK1']) #Creates a new column called HourlyWage and calculates it by doing AnnualIncome / UHRSWORKT * 52
cleaned_df['Over40Hours'] = (cleaned_df['UHRSWORKT'] > 40).astype(int) #Creates a new column called Over40Hours and filters out the UHRSWORKT column to show results over 40 hours
print(cleaned_df.head())

final_columns = ['SEX', 'UHRSWORKT', 'EDUC', 'AnnualIncome', 'Occupation Title', 'OCC Code', 'HourlyWage', 'Over40Hours'] #Labels wanted columns as final_columns
df_final = cleaned_df[final_columns].copy() #Creates a copy of the dataframe with only the wanted columns present
df_final = df_final[(df_final['UHRSWORKT'] < 60) & (df_final['UHRSWORKT'] > 30)] #Filters out results to only show hours greater than 30, but less than 60
df_final = df_final[(df_final['AnnualIncome'] < 250000) & (df_final['AnnualIncome'] > 10000)] #Filters out results to only show AnnualIncome greater than 10,000 and less than 250,000
df_final.head()

"""# Graphs"""

df_final['UHRSWORKT'].plot(kind='hist', bins=20, edgecolor='black')
plt.xlabel('Hours Worked')
plt.ylabel('Frequency')
plt.title('Distribution of Hours Worked')

df_final['AnnualIncome'].plot(kind='box')
plt.ylabel('Frequency')
plt.title('Distribution of Annual Income')

"""# Statistical Analysis"""

import scipy.stats as stats
import numpy as np

male_income = df_final[df_final['SEX'] == 1]['AnnualIncome'] #Seaparates data for males income
female_income = df_final[df_final['SEX'] == 2]['AnnualIncome'] #Separates data for females income

mean_male = male_income.mean() #Calculates the mean income for males
std_male = male_income.std() #Calculates the standard deviation for males
n_male = len(male_income) #Calculates the number of males

mean_female = female_income.mean() #Calculates the mean income for females
std_female = female_income.std() #Calculates the standard deviation for females
n_female = len(female_income) #Calculates the number of females

mean_difference = mean_male - mean_female #Calculates the difference in income for both genders

standard_error = np.sqrt((std_male**2 / n_male) + (std_female**2 / n_female)) #Calculates the standard of error

degrees_of_freedom = n_male + n_female - 2 #Calculates the degrees of freedom

lower_ci, upper_ci = stats.t.interval(0.95, df=degrees_of_freedom, loc=mean_difference, scale=standard_error) #Finds the upper and lower confidence intervals for income in males and females

print(f"Mean annual income for males: ${mean_male:,.2f}")
print(f"Mean annual income for females: ${mean_female:,.2f}")
print(f"Difference in mean income ${mean_difference:,.2f}")
print(f"95% confidence interval for the difference in annual income: ${lower_ci:,.2f}, ${upper_ci:,.2f}")

"""# Predictive Model"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

income_threshold = df_final['AnnualIncome'].quantile(0.75) #Finds the 75th percentile of annual income
df_final['HighEarner'] = (df_final['AnnualIncome'] > income_threshold).astype(int) #A new column called HighEarner is made, if a persons annual income is above the income threshold, it's labeled 1, otherwise 0

print(f"HighEarner threshold (75th percentile of AnnualIncome): ${income_threshold:,.2f}")
print("\nDistribution of HighEarner status:")
print(df_final['HighEarner'].value_counts())

features = ['SEX', 'UHRSWORKT', 'EDUC', 'Over40Hours'] #The columns used to predict if someone is a high earner
target = 'HighEarner' #The column we're trying to predict

X = df_final[features] #Creates a new table x containing only our predictor variables
y = df_final[target] #Creates a list y containing the high earner status for each person

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42) #Splits the data into training and testing sets. 70% of the data will train and 30% will test

dtree = DecisionTreeClassifier(random_state=42) #Creates an empty decision tree model
dtree.fit(X_train, y_train) #Learns from the x_train predictor variables and y_train high earner status data to find rules that predict high earner

print("\nKey Predictor Variables (Feature Importance):")
feature_importances = pd.Series(dtree.feature_importances_, index=features).sort_values(ascending=False) #After training, the decision tree can tell us how important each feature was in making its predictions
print(feature_importances)

from sklearn.metrics import accuracy_score, classification_report
y_pred = dtree.predict(X_test) #The trained dtree model makes predictions on the X_test data, y_pred contains these predictions
print(f"\nModel Accuracy: {accuracy_score(y_test, y_pred):.2f}") #Compares the model's predictions to the actual high earner status and calculates overall accuracy
print("\nClassification Report:\n", classification_report(y_test, y_pred)) #Provides a more detailed breakdown of how well the model performed